In [1]:
import pandas as pd
import matplotlib.pyplot as plt     
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv(r'E:\DA full projects\Medical Appointment No Shows\Raw Files\medical_appointment.csv')
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [6]:
df.dtypes

PatientId                     float64
AppointmentID                   int64
Gender                         object
ScheduledDay      datetime64[ns, UTC]
AppointmentDay    datetime64[ns, UTC]
Age                             int64
Neighbourhood                  object
Scholarship                     int64
Hipertension                    int64
Diabetes                        int64
Alcoholism                      int64
Handcap                         int64
SMS_received                    int64
No-show                        object
dtype: object

In [4]:
#No show vs showed counts
df.groupby('No-show')['No-show'].count()

No-show
No     88208
Yes    22319
Name: No-show, dtype: int64

In [5]:
#convert schedule and appointment columns to date-time
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

In [7]:
df['No-show'].count()

np.int64(110527)

In [7]:
#No show by Gender
df.groupby(['Gender', 'No-show'])['No-show'].count()

Gender  No-show
F       No         57246
        Yes        14594
M       No         30962
        Yes         7725
Name: No-show, dtype: int64

In [8]:
#No show by Neighborhood
df.groupby(['Neighbourhood', 'No-show'])['No-show'].count()

Neighbourhood    No-show
AEROPORTO        No            7
                 Yes           1
ANDORINHAS       No         1741
                 Yes         521
ANTÔNIO HONÓRIO  No          221
                            ...
TABUAZEIRO       Yes         573
UNIVERSITÁRIO    No          120
                 Yes          32
VILA RUBIM       No          710
                 Yes         141
Name: No-show, Length: 160, dtype: int64

In [9]:
#Data cleaning - Renaming columns
df = df.rename(columns={'Hipertension': 'Hypertension'})
df = df.rename(columns={'Handcap': 'Disability_Count'})

In [10]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [11]:
#Checking to make sure disability counts are 0 through 4
df['Disability_Count'].unique()

array([0, 1, 2, 3, 4])

In [12]:
#Checking ages to make sure there are not any that don't make sense
df['Age'].unique()

array([ 62,  56,   8,  76,  23,  39,  21,  19,  30,  29,  22,  28,  54,
        15,  50,  40,  46,   4,  13,  65,  45,  51,  32,  12,  61,  38,
        79,  18,  63,  64,  85,  59,  55,  71,  49,  78,  31,  58,  27,
         6,   2,  11,   7,   0,   3,   1,  69,  68,  60,  67,  36,  10,
        35,  20,  26,  34,  33,  16,  42,   5,  47,  17,  41,  44,  37,
        24,  66,  77,  81,  70,  53,  75,  73,  52,  74,  43,  89,  57,
        14,   9,  48,  83,  72,  25,  80,  87,  88,  84,  82,  90,  94,
        86,  91,  98,  92,  96,  93,  95,  97, 102, 115, 100,  99,  -1])

In [54]:
df[df['Age'] == -1]

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show
99832,4.659432e+14,5775010,F,2016-06-06 08:58:13+00:00,2016-06-06 00:00:00+00:00,-1,ROMÃO,0,0,0,0,0,0,No

In [13]:
#Deleting the row that had the age error since I can't confirm the age based on the data itself
df.drop(99832)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [ ]:
#Check to see how many days existed between scheduled day and appointment day for each appointment
df['lead_time_days'] = (df['AppointmentDay'].dt.normalize() - df['ScheduledDay'].dt.normalize()).dt.days

In [57]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show,lead_time_days
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,0
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,0
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,0
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,0
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,MARIA ORTIZ,0,0,0,0,0,1,No,35
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,MARIA ORTIZ,0,0,0,0,0,1,No,35
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,MARIA ORTIZ,0,0,0,0,0,1,No,41
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,MARIA ORTIZ,0,0,0,0,0,1,No,41
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,MARIA ORTIZ,0,0,0,0,0,1,No,41

In [ ]:
#Checking No-show vs Show counts
df.groupby('No-show')['No-show'].count()

No-show
No     88208
Yes    22319
Name: No-show, dtype: int64

In [15]:
#Checking percentages of no shows
percentages = df['No-show'].value_counts(normalize = True).round(3) * 100
print(percentages)

No-show
No     79.8
Yes    20.2
Name: proportion, dtype: float64

In [16]:
#Checking counts of no shows based on day of week

df2 = df[df['No-show'] == 'Yes']

df2['App_day'] = df['AppointmentDay'].dt.day_name()

df2.groupby('App_day')['No-show'].count()

C:\Users\Joshua\AppData\Local\Temp\ipykernel_30336\2269572533.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['App_day'] = df['AppointmentDay'].dt.day_name()

App_day
Friday       4037
Monday       4690
Saturday        9
Thursday     3338
Tuesday      5152
Wednesday    5093
Name: No-show, dtype: int64

In [17]:
#Creating new column Lead time bucket to compare No-show rates based on how many days each patient had between scheduled day and appointment day

df['lead_time_bucket'] = df['lead_time_days'].apply(lambda x: 
                                              'Same Day' if x == 0 
                                              else 'Short (1-3 Days)' if 1 <= x <=3
                                              else 'Within a week' if 4 <= x <=7
                                              else 'Long lead (8+ days)' if x >= 8
                                              else 'Unknown')

In [63]:
df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show,lead_time_days,lead_time_bucket
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,0,Same Day
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,0,Same Day
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,0,Same Day
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,0,Same Day
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,0,Same Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,MARIA ORTIZ,0,0,0,0,0,1,No,35,Long lead (8+ days)
110523,3.596266e+12,5650093,F,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,MARIA ORTIZ,0,0,0,0,0,1,No,35,Long lead (8+ days)
110524,1.557663e+13,5630692,F,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,MARIA ORTIZ,0,0,0,0,0,1,No,41,Long lead (8+ days)
110525,9.213493e+13,5630323,F,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,MARIA ORTIZ,0,0,0,0,0,1,No,41,Long lead (8+ days)
110526,3.775115e+14,5629448,F,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,MARIA ORTIZ,0,0,0,0,0,1,No,41,Long lead (8+ days)

In [21]:
#Determining if wait time affects no show rate
df.groupby('lead_time_bucket').agg(total_appointments = ('lead_time_bucket', 'count'), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index().sort_values(by = 'no_show_rate')

      lead_time_bucket  total_appointments  no_show_rate
1             Same Day               38563          4.65
2     Short (1-3 Days)               14675         22.89
4        Within a week               17510         25.20
0  Long lead (8+ days)               39774         32.06
3              Unknown                   5        100.00

In [11]:
#Determining if Age affects no show rate

df['age_bracket'] = df['Age'].apply(lambda x: 
                                              'Child (1 - 12)' if 0 <= x <= 12 
                                              else 'Teen (13 - 19)' if  13 <= x <= 19
                                              else 'Young Adult (20 - 39)' if 20 <= x <= 39
                                              else ' Adult (40 - 59)' if 40 <= x <= 59
                                              else 'Senior (60+)')

df.groupby('age_bracket').agg(total_appointments = ('lead_time_bucket', 'count'), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

             age_bracket  total_appointments  no_show_rate
0        Adult (40 - 59)               30072         18.81
1         Child (1 - 12)               21036         20.47
2           Senior (60+)               21174         15.31
3         Teen (13 - 19)                9375         25.96
4  Young Adult (20 - 39)               28870         23.14

In [18]:
#Do SMS reminders help
df['SMS_received'].unique()
df.groupby('SMS_received').agg(sms_type_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

   SMS_received  sms_type_count  no_show_rate
0             0           75045         16.70
1             1           35482         27.57

In [20]:
#WHich neighborhoods have the highest risk?

pd.set_option('display.max.rows', 9999999)
neighborhoods = df.groupby('Neighbourhood').agg(appointment_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).query('appointment_count >= 100').round(2).reset_index().nlargest(15, 'no_show_rate')
neighborhoods['risk_rank'] = neighborhoods['no_show_rate'].rank(ascending = False, method = 'dense')
neighborhoods

        Neighbourhood  appointment_count  no_show_rate  risk_rank
63      SANTOS DUMONT               1276         28.92        1.0
54      SANTA CECÍLIA                448         27.46        2.0
55        SANTA CLARA                506         26.48        3.0
32            ITARARÉ               3514         26.27        4.0
36  JESUS DE NAZARETH               2853         24.40        5.0
27              HORTO                175         24.00        6.0
30   ILHA DO PRÍNCIPE               2266         23.48        7.0
8           CARATOÍRA               2565         23.04        8.0
0          ANDORINHAS               2262         23.03        9.0
49       PRAIA DO SUÁ               1288         22.83       10.0
26           GURIGICA               2018         22.60       11.0
5      BENTO FERREIRA                858         22.49       12.0
46     PARQUE MOSCOSO                802         22.32       13.0
40            MARUÍPE               1902         22.29       14.0
17         DO MOSCOSO                413         22.28       15.0

In [68]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show,lead_time_days,lead_time_bucket,age_bracket
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,0,Same Day,Senior (60+)
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,0,Same Day,Adult (40 - 59)
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,0,Same Day,Senior (60+)
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,0,Same Day,Child (1 - 12)
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,0,Same Day,Adult (40 - 59)

In [ ]:
#Risk scoring per patient

df = df.sort_values(['PatientId', 'AppointmentDay'])

df['prior_appointments'] = (df.groupby('PatientId').cumcount())

df['prior_no_shows'] = (df['No-show'].eq('Yes')
    .groupby(df['PatientId'])
    .cumsum()
    .shift(1)
    .fillna(0)
    .astype(int)
)

result = df[['PatientId', 'AppointmentID', 'AppointmentDay', 'No-show', 'prior_appointments', 'prior_no_shows']].sort_values(['PatientId', 'AppointmentDay'])

result

In [ ]:
#Creating a risk assessment table

df = df.sort_values(['PatientId', 'AppointmentDay', 'AppointmentID']).copy()

df['prior_appointments'] = (df.groupby('PatientId').cumcount())

df['no_show_flag'] = df['No-show'].eq('Yes').astype(int)

df['prior_no_shows'] = (df.groupby('PatientId')['no_show_flag']
      .cumsum()
      .groupby(df['PatientId'])
      .shift(1)
      .fillna(0)
      .astype(int)
)

df['prior_no_show_rate'] = (df['prior_no_shows'].div(df['prior_appointments'].replace(0, np.nan)).round(2))

conditions = [
    df['prior_appointments'].eq(0),

    (df['prior_no_show_rate'].ge(0.5)) |
    (df['lead_time_days'].ge(8)),

    (df['prior_no_show_rate'].ge(0.2)) |
    (df['lead_time_days'].between(4, 7))
]

choices = [
    'New Patient - Monitor',
    'High Risk',
    'Medium Risk'
]

df['risk_tier'] = np.select(conditions, choices, default='Low Risk')

high_risk_appointments = (
    df[
        
        [
            'PatientId',
            'AppointmentID',
            'AppointmentDay',
            'Neighbourhood',
            'lead_time_days',
            'prior_appointments',
            'prior_no_shows',
            'prior_no_show_rate',
            'risk_tier'
        ]
    ]
    .sort_values('AppointmentDay')
    
)

high_risk_appointments

,PatientId,AppointmentID,AppointmentDay,Neighbourhood,lead_time_days,prior_appointments,prior_no_shows,prior_no_show_rate,risk_tier
148,5.637725e+14,5641470,2016-04-29 00:00:00+00:00,ITARARÉ,0,0,0,NaN,New Patient - Monitor
409,1.418162e+13,5510054,2016-04-29 00:00:00+00:00,JABOUR,37,0,0,NaN,New Patient - Monitor
1160,9.271495e+13,5515566,2016-04-29 00:00:00+00:00,ESTRELINHA,32,0,0,NaN,New Patient - Monitor
1613,4.119513e+10,5638121,2016-04-29 00:00:00+00:00,GURIGICA,0,0,0,NaN,New Patient - Monitor
2339,4.949758e+12,5618693,2016-04-29 00:00:00+00:00,FORTE SÃO JOÃO,3,0,0,NaN,New Patient - Monitor
...,...,...,...,...,...,...,...,...,...
97419,6.191925e+13,5702346,2016-06-08 00:00:00+00:00,CENTRO,23,1,0,0.0,High Risk
100436,6.188116e+13,5686358,2016-06-08 00:00:00+00:00,JESUS DE NAZARETH,28,1,0,0.0,High Risk
97076,6.186989e+13,5677523,2016-06-08 00:00:00+00:00,JABOUR,29,2,2,1.0,High Risk
101100,8.368524e+11,5648889,2016-06-08 00:00:00+00:00,MARIA ORTIZ,37,1,0,0.0,High Risk
94717,5.351772e+13,5774531,2016-06-08 00:00:00+00:00,SANTA MARTHA,2,6,0,0.0,Low Risk

In [ ]:
#Table exports
df.to_csv(r'E:\DA full projects\Medical Appointment No Shows\Raw Files\ + medical_appointments_CLEANED.csv')
high_risk_appointments.to_csv(r'E:\DA full projects\Medical Appointment No Shows\Raw Files\ + appointment_risk.csv')

In [ ]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [ ]:
#No show by hypertension diagnosis
df.groupby('Hypertension').agg(no_show_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

   Hypertension  no_show_count  no_show_rate
0             0          88726          20.9
1             1          21801          17.3

In [ ]:
#No show by diabetes diagnosis

df.groupby('Diabetes').agg(no_show_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

   Diabetes  no_show_count  no_show_rate
0         0         102584         20.36
1         1           7943         18.00

In [ ]:
#No show by alcoholism diagnosis

df.groupby('Alcoholism').agg(no_show_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

   Alcoholism  no_show_count  no_show_rate
0           0         107167         20.19
1           1           3360         20.15

In [ ]:
#No show by disability Count

df.groupby('Disability_Count').agg(no_show_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

   Disability_Count  no_show_count  no_show_rate
0                 0         108286         20.24
1                 1           2042         17.92
2                 2            183         20.22
3                 3             13         23.08
4                 4              3         33.33

In [ ]:
#No-Show by scholarship

df.groupby('Scholarship').agg(no_show_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

   Scholarship  no_show_count  no_show_rate
0            0          99666         19.81
1            1          10861         23.74

In [43]:
#No show counts and rates by gender

df.groupby('Gender').agg(appointment_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

  Gender  appointment_count  no_show_rate
0      F              71840         20.31
1      M              38687         19.97

In [22]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show,lead_time_days,lead_time_bucket
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,0,Same Day
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,0,Same Day
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,0,Same Day
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,0,Same Day
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,0,Same Day

In [25]:
df.dtypes

PatientId                       float64
AppointmentID                     int64
Gender                           object
ScheduledDay        datetime64[ns, UTC]
AppointmentDay      datetime64[ns, UTC]
Age                               int64
Neighbourhood                    object
Scholarship                       int64
Hypertension                      int64
Diabetes                          int64
Alcoholism                        int64
Disability_Count                  int64
SMS_received                      int64
No-show                          object
lead_time_days                    int64
lead_time_bucket                 object
dtype: object

In [46]:
df['schedule_time'] = df['ScheduledDay'].dt.time

In [30]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show,lead_time_days,lead_time_bucket,schedule_time
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,0,Same Day,00:00:00
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,0,Same Day,00:00:00
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,0,Same Day,00:00:00
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,0,Same Day,00:00:00
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,0,Same Day,00:00:00

In [47]:
t = pd.to_datetime('12:00:00').time()
df['scheduled_time_frame'] = df['schedule_time'].apply(lambda x: 'Before Noon' if x <= t else 'Afternoon')

In [48]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hypertension,Diabetes,Alcoholism,Disability_Count,SMS_received,No-show,lead_time_days,lead_time_bucket,schedule_time,scheduled_time_frame
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No,0,Same Day,18:38:08,Afternoon
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No,0,Same Day,16:08:27,Afternoon
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No,0,Same Day,16:19:04,Afternoon
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,0,Same Day,17:29:31,Afternoon
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No,0,Same Day,16:07:23,Afternoon

In [49]:
#no show rate by scheduled time frame
df.groupby('scheduled_time_frame').agg(appointment_count = ('No-show', lambda x: (x == 'Yes').count()), no_show_rate = ('No-show', lambda x: (x == 'Yes').mean() * 100)).round(2).reset_index()

  scheduled_time_frame  appointment_count  no_show_rate
0            Afternoon              42045         22.37
1          Before Noon              68482         18.85

In [45]:
df['schedule_time'].unique()

array([datetime.time(0, 0)], dtype=object)